export interface OptimizedImage {
  id: string;
  originalName: string;
  blur: string; // base64 data URL for placeholder
  sources: {
    webp: {
      sm: string;
      md: string;
      lg: string;
      xl: string;
    };
    avif: {
      sm: string;
      md: string;
      lg: string;
      xl: string;
    };
  };
}

// Import generated manifest
// Note: This file will be generated by the optimization script
// We use a try-catch or dynamic import in a real app, but for type safety we assume it exists
// or we can use a require with a fallback
let manifest: Record<string, OptimizedImage> = {};

try {
  manifest = require('@/public/images/optimized/manifest.json');
} catch (e) {
  console.warn('Image manifest not found. Run npm run optimize-images');
}

export function getOptimizedImage(originalPath: string): OptimizedImage | null {
  // Extract filename without extension and sanitize to match ID generation logic
  const filename = originalPath.split('/').pop()?.replace(/\.[^/.]+$/, "") || "";
  const id = filename
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[()]/g, '')
    .replace(/[^a-z0-9-]/g, '');
    
  return manifest[id] || null;
}
